---

- hosts: '{{ hostgroup }}'
  user: '{{ ansibleUser }}'
  become_user: root
  become: true
  vars:
    hostgroup: "production"
    timezone: "America/Chicago"
    dnsDomainName: "d1.mors.io"
    ansibleUser: "ansible"
    adminEmail: "admins@mors.io"
    adminUser: "morsadmin"
    proxmoxHost: false
    qemuGuest: true
    updatePackages: true
    updateDistro: false
    systemHardening: true

    dmzSetup: true


    setupCommon: true
    linuxGitHubProfile: "https://github.com/micah-mitchell/linuxProfile.git"
    linuxGitHubKeys: "https://github.com/micah-mitchell.keys"

    setupCertificates: true

    setupNTP: true
    ntpService: "timesyncd"

    setupHostname: true

    setupMail: true
    mailService: "postfix"

    setupSSH: true

    setupFirewall: true
    firewallService: "ufw"
    
    setupLogging: true
    loggingService: "rsyslog"

    setupSerial: true

    setupSwap: true
    swapSize: "512M"
    swapFile: "/swapfile"

    setupAutoUpdate: true

    setupFail2ban: true

    setupDocker: false

    setupAuditd: false

  roles:
   - updates
   - common
   - certificates
   - ntp
   - hostname
   - mail
   - ssh
   - qemu
   - firewall
   - logging
   - serial
   - swap
   - auto-update
   - fail2ban
   - docker
   - auditd
   - cleanup

