---

- hosts: '{{ hostgroup }}'
  user: '{{ ansibleUser }}'
  become_user: root
  become: true
  vars:
    hostgroup: "production"
    timezone: "America/Chicago"
    dnsDomainName: "d1.mors.io"
    ansibleUser: "ansible"
    adminEmail: "admins@mors.io"
    adminUser: "morsadmin"
    proxmoxHost: false
    qemuGuest: true
    updatePackages: true
    updateDistro: false
    systemHardening: true

    dmzSetup: true
    swapSetup: true
    swapSize: "512M"

    setupCommon: true
    linuxGitHubProfile: "https://github.com/micah-mitchell/linuxProfile.git"
    linuxGitHubKeys: "https://github.com/micah-mitchell.keys"

    setupNTP: true
    ntpService: "timesyncd"

    setupHostname: true

    setupMail: true
    mailService: "postfix"

    setupSSH: true

    setupFirewall: true
    firewallService: "ufw"
    
    setupLogging: true
    loggingService: "rsyslog"

    setupAutoUpdate: true

    setupDocker: false

    setupSerial: true

    setupFail2ban: true

  roles:
   - updates
   - common
   - ntp
   - hostname
   - mail
   - ssh
   - qemu
   - firewall
   - logging
   - docker
   - serial
   - fail2ban
   - auto-update
   - cleanup
   #- nginx

