---
### Package Management
- name: Install Packages
  ansible.builtin.apt:
    name:
      - vim
      - unzip
      - htop
      - iftop
      - iotop
      - mtr
      - ncdu
      - multitail
      - tmux
      - git
      - sysstat
      - sudo
    state: present
    update_cache: yes

### Profile Setup
- name: Install system bash.bashrc file
  ansible.builtin.copy:
    src: files/bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: '0644'

- name: Create skel files
  ansible.builtin.copy:
    src: files/skel/
    dest: /etc/skel/
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
      
- name: Add skel files to root
  ansible.builtin.copy:
    src: /etc/skel/
    dest: /root/
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
    remote_src: true


### User Setup
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create {{ ansibleUser }}
  ansible.builtin.user:
    name: "{{ ansibleUser }}"
    password_lock: true
    groups: users,admin
    shell: /bin/bash
    state: present

- name: Add Ansible Pub Key to {{ ansibleUser }}
  authorized_key:
    user: '{{ ansibleUser }}'
    key: '{{ item }}'
    state: present
    exclusive: true
  with_file:
    - files/ansible.pub

- name: Add Admin Pub Key to root
  authorized_key:
    user: root
    key: '{{ item }}'
    state: present
    exclusive: true
  with_file:
    - files/admin.pub
  when: proxmoxHost == false

- name: Add Admin Pub Key to root
  authorized_key:
    user: root
    key: '{{ item }}'
    state: present
    exclusive: true
    path: ~/.ssh/authorized_keys2
  with_file:
    - files/admin.pub
  when: proxmoxHost == true

- name: Create {{ adminUser }}
  ansible.builtin.user:
    name: "{{ adminUser }}"
    password_lock: true
    groups: sudo
    home: '/home/{{ adminUser }}'
    shell: /bin/bash
    state: present

- name: Ensure {{ adminUser }} has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ adminUser }}"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add Git Pub Keys to {{ adminUser }}
  authorized_key:
    user: '{{ adminUser }}'
    key: '{{ linuxGitHubKeys }}'
    state: present
    exclusive: false

- name: Add Admin Pub Key to {{ adminUser }}
  authorized_key:
    user: '{{ adminUser }}'
    key: '{{ item }}'
    state: present
    exclusive: false
  with_file:
    - files/admin.pub

#- name: "Add skel files to {{ adminUser }}"
#  ansible.builtin.copy:
#    src: files/skel/
#    dest: "/home/{{ adminUser }}/"
#    owner: "{{ adminUser }}"
#    group: "{{ adminUser }}"
#    mode: 0644
#    directory_mode: 0776

- name: Checkout Git linuxProfile
  ansible.builtin.git:
    repo: '{{ linuxGitHubProfile }}'
    dest: /tmp/linuxProfile
    accept_hostkey: true

- name: Add linuxProfile files to {{ adminUser }}
  ansible.builtin.copy:
    src: /tmp/linuxProfile/
    dest: '/home/{{ adminUser }}/'
    owner: "{{ adminUser }}"
    group: "{{ adminUser }}"
    mode: '0644'
    directory_mode: '0755'
    remote_src: true

- name: Ensure Proper Permissions of {{ adminUser }} home folder
  ansible.builtin.file:
    path: '/home/{{ adminUser }}'
    state: directory
    mode: '0755'
    owner: "{{ adminUser }}"
    group: "{{ adminUser }}"
